import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart' hide Ink;
import 'package:google_mlkit_digital_ink_recognition/google_mlkit_digital_ink_recognition.dart';
import 'package:provider/provider.dart';

import '../providers/settings_provider.dart';
import '../utils/painter.dart';

class DrawingOverlay extends StatefulWidget {
  final Function(Ink)? callback;
  final Widget child;

  const DrawingOverlay({super.key, this.callback, required this.child});

  @override
  State<DrawingOverlay> createState() => _DrawingOverlayState();
}

class _DrawingOverlayState extends State<DrawingOverlay> {
  final Ink _ink = Ink();
  Timer? _timer;

  void onPanStart(DragStartDetails details) {
    final point = details.localPosition;
    final StrokePoint strokePoint = StrokePoint(
        x: point.dx, y: point.dy, t: DateTime.now().millisecondsSinceEpoch);
    final Stroke stroke = Stroke();
    stroke.points.add(strokePoint);
    _ink.strokes.add(stroke); // start new stroke
  }

  void onPanUpdate(DragUpdateDetails details) {
    final point = details.localPosition;
    final List<StrokePoint> points = _ink.strokes.last.points;
    final distance =
        pow(point.dx - points.last.x, 2) + pow(point.dy - points.last.y, 2);
    // ignore points generated by another finger
    if (distance <= 20000) {
      final StrokePoint strokePoint = StrokePoint(
          x: point.dx, y: point.dy, t: DateTime.now().millisecondsSinceEpoch);
      points.add(strokePoint); // add point to current stroke
      if (strokePoint.t - points.first.t >= 20) {
        _timer?.cancel(); // cancel timer if valid stroke has been detected
        setState(() {});
      }
    }
  }

  void onPanEnd(DragEndDetails details) {
    final List<StrokePoint> points = _ink.strokes.last.points;
    // ignore short strokes
    if (points.last.t - points.first.t >= 20) {
      widget.callback!(_ink); // send strokes to callback
      _timer = Timer(
          Duration(milliseconds: context.read<Settings>().getDrawingTimeout()),
          () {
        _ink.strokes.clear();
        setState(() {});
      });
    } else {
      _ink.strokes.removeLast();
    }
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onPanStart: onPanStart,
      onPanUpdate: onPanUpdate,
      onPanEnd: onPanEnd,
      child: Stack(
        children: [
          widget.child,
          CustomPaint(painter: StrokePainter(context: context, ink: _ink)),
        ],
      ),
    );
  }
}
