name:  Build_release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    - name: Get dependencies
      run: flutter pub get
#    - name: Run tests
#     run: flutter test
    - name: Build APK
      run: flutter build apk
    - name: Build App Bundle
      run: flutter build appbundle

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload App Bundle
      uses: actions/upload-artifact@v2
      with:
        name: app-release-aab
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Create GitHub Release and Upload APK & AAB
      if: github.event_name == 'release'
      run: |
        gh release create ${{ github.event.release.tag_name }} \
          build/app/outputs/flutter-apk/app-release.apk \
          build/app/outputs/bundle/release/app-release.aab \
          --title "${{ github.event.release.name }}" \
          --notes "${{ github.event.release.body }}" \
          --repo ${{ github.repository }} \
