name: Build apk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      # - run: flutter format --set-exit-if-changed
      # - run: flutter analyze
      # - run: flutter test
      - run: flutter build apk
      # - run: flutter build appbundle
      - name: Clone repository
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
